In [257]:
import pandas as pd
import numpy as np
import sklearn
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

In [258]:
df=pd.read_csv("/content/Social_Network_Ads - Social_Network_Ads.csv")

In [259]:
df.sample(5)

      User ID  Gender  Age  EstimatedSalary  Purchased
287  15761950  Female   48           138000          1
232  15813113    Male   40           107000          1
352  15587419  Female   42            90000          1
179  15673367  Female   31            34000          0
394  15757632  Female   39            59000          0

In [260]:
df.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [261]:
df=df.drop(columns="User ID")

In [262]:
x=df.drop(columns="Purchased")

In [263]:
y=df["Purchased"]

In [264]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [265]:
from sklearn.compose import ColumnTransformer

In [266]:
transformer=ColumnTransformer([
    ("tnf1",StandardScaler(),["Age","EstimatedSalary"]),
    ("tnf2",OneHotEncoder(sparse_output=False,drop="first"),["Gender"])
],remainder="passthrough")

In [267]:
transformer.fit(x_train)

ColumnTransformer(remainder='passthrough',
                  transformers=[('tnf1', StandardScaler(),
                                 ['Age', 'EstimatedSalary']),
                                ('tnf2',
                                 OneHotEncoder(drop='first',
                                               sparse_output=False),
                                 ['Gender'])])

In [268]:
x_train_new=transformer.transform(x_train)

In [269]:
x_test_new=transformer.transform(x_test)

In [270]:
x_train_new=pd.DataFrame(x_train_new)
x_test_new=pd.DataFrame(x_test_new)

In [271]:
x_train_new.head(2)

          0         1    2
0 -1.066752 -0.386344  0.0
1  0.797535 -1.229939  1.0

In [272]:
np.round(x_train_new.describe(),1)

           0      1      2
count  320.0  320.0  320.0
mean    -0.0    0.0    0.5
std      1.0    1.0    0.5
min     -1.9   -1.6    0.0
25%     -0.8   -0.8    0.0
50%     -0.1    0.0    0.5
75%      0.7    0.5    1.0
max      2.2    2.3    1.0